#!/bin/tclsh
package require udp

set addr 127.0.0.1
set port 60440

set sock [udp_open]
fconfigure $sock -buffering none -translation binary

proc dest {addr port} {
    # puts "-> $addr $port"
    fconfigure $::sock -remote [list $addr $port]
}

dest $addr $port

proc wire {msg} {
    puts -nonewline $::sock $msg
}

#  9 21 33 45 57 69
while {1} {
  set f 27.5
  for {set i 9} {$i <= 69} {incr i 12} {
    set j [expr 69 - $i]
    wire "\[ v0 n${i} l1 v1 n${j} l1"
    after 200
    wire "v0 l0 v1 n${j} l0 \]"
    after 50
  }
}
