#!/bin/tclsh
package require udp

set addr 127.0.0.1
set port 60440

set sock [udp_open]
fconfigure $sock -buffering none -translation binary

proc dest {addr port} {
    # puts "-> $addr $port"
    fconfigure $::sock -remote [list $addr $port]
}

dest $addr $port

proc wire {msg} {
    puts -nonewline $::sock "\[ $msg \]"
}

set all 500
set on [expr $all / 2]
set off [expr $all - $on]

#  9 21 33 45 57 69
wire "S0 v10 w1 a8 J1 K500 Q3 l0 E.2,.1,.2,.5"
wire "v10 >0 >1 a0"

set vp 0
while {1} {
  set f 27.5
  for {set i 9} {$i <= 69} {incr i 12} {
    set v0 [expr $i + 12]
    set j [expr $i + 12.2]
    set v1 $j
    
    set out "v0 n${v0} l1 v1 n${v1} l1"
    puts " ON $out"
    wire $out
    
    after $on
    
    set out "v0 l0 v1 l0"
    puts "OFF $out"
    wire $out
    after $off
    
    incr vp 2
    
    if {$vp > 7} {set vp 0}
  }
}
