CC = x86_64-w64-mingw32-gcc
AR = x86_64-w64-mingw32-ar

OUT = build/win

EXE = \
	$(OUT)/skred.exe \
  #

all : $(EXE)

LIB = \
	-lm \
  -pthread \
	-lpthread \
  -lws2_32 \
  #

COPTS = \
  -D_GNU_SOURCE \
  -Wall \
  -g

wav2data : wav2data.c miniwav.o
	$(CC) -g -D_GNU_SOURCE $^ -o $@

$(OUT)/util.o : util.c util.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/miniwav.o : miniwav.c miniwav.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/amysamples.o : amysamples.c amysamples.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/retro.o: retro/retro.c retro/retro.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/synth.o: synth.c synth.h synth-types.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/skqueue.o : skqueue.c skqueue.h
	$(CC) $(COPTS) -c skqueue.c -o $(OUT)/skqueue.o

$(OUT)/seq.o: seq.c seq.h
	# $(CC) $(COPTS) -c $< -o $@
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/udp.o: udp.c udp.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/ands.o: ands.c ands.h
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/skode.o: skode.c skode.h ands.h $(OUT)/ands.o
	$(CC) $(COPTS) -Wno-multichar -c $< -o $@

$(OUT)/skred-mem.o : skred-mem.c
	$(CC) $(COPTS) -c $< -o $@

$(OUT)/skred.o: skred.c
	$(CC) $(COPTS) -c $< -o $@

OBJS = \
  $(OUT)/skred.o \
  $(OUT)/miniwav.o \
  $(OUT)/amysamples.o \
  $(OUT)/synth.o \
	$(OUT)/retro.o \
  $(OUT)/seq.o \
  $(OUT)/skode.o \
  $(OUT)/udp.o \
  $(OUT)/miniaudio.o \
  $(OUT)/skred-mem.o \
  $(OUT)/util.o \
  $(OUT)/ands.o \
  $(OUT)/skqueue.o \
  #

$(OUT)/skred.exe : $(OBJS)
	$(CC) $(COPTS) $^ -o $@ $(LIB) -static

$(OUT)/miniaudio.o: miniaudio.c miniaudio.h
	$(CC) -c $< -o $@

clean :
	rm -f $(OUT)/*.o
	rm -f $(EXE)