name: Skred CI & Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  check_build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-linux
            os: ubuntu-latest
          - target: x86_64-windows
            os: ubuntu-latest
          - target: aarch64-macos
            os: macos-latest
          - target: x86_64-macos
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Install ALSA (Linux Only)
        if: matrix.target == 'x86_64-linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Verify Compilation
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-linux" ]]; then
            zig build
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            MACOS_SDK_PATH=$(xcrun --show-sdk-path)
            # -F adds the Framework search path inside the SDK
            zig build -Dtarget=${{ matrix.target }} --sysroot "$MACOS_SDK_PATH" -F "$MACOS_SDK_PATH/System/Library/Frameworks"
          else
            zig build -Dtarget=${{ matrix.target }}
          fi

  create_release:
    needs: check_build
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-linux
            os: ubuntu-latest
          - target: x86_64-windows
            os: ubuntu-latest
          - target: aarch64-macos
            os: macos-latest
          - target: x86_64-macos
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Install ALSA (Linux Only)
        if: matrix.target == 'x86_64-linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Build Zip
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-linux" ]]; then
            zig build zip -Dversion=${{ github.ref_name }}
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            MACOS_SDK_PATH=$(xcrun --show-sdk-path)
            zig build zip -Dtarget=${{ matrix.target }} -Dversion=${{ github.ref_name }} --sysroot "$MACOS_SDK_PATH" -F "$MACOS_SDK_PATH/System/Library/Frameworks"
          else
            zig build zip -Dtarget=${{ matrix.target }} -Dversion=${{ github.ref_name }}
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: zig-out/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
